export const EXTERNAL_LINKS = {
  docs: "https://docs.xone.org/",
  website: "https://xone.org/",
  faucet: "https://faucet.xone.org/en",
  Telegram: "https://t.me/hello_xonechain",
  Twitter: "https://x.com/xone_chain",
  Medium: "https://medium.com/@xone_chain",
  Youtube: "https://www.youtube.com/@HelloXone",
  Github: "https://github.com/hello-xone",
  Reddit: "https://www.reddit.com/r/XoneChain/",
  Xone_Scan: "https://xonescan.com/",
  ChatMe:"https://share.chatme.global/share/group/ztgqmws2k?lang=en&mode=light",
  Discord: "https://discord.com/invite/Du9y2GHV",
  Suggest_Dapp:
    "https://github.com/hello-xone/official_docs/issues/new?template=suggest_dapp.yaml",
  Official_Email:"hello@xone.org",
  Support_Email:"support@xone.org",
  Business_Email:"business@xone.org",
  Newsletter_Email:"newsletter@xone.org",
  Developers_Email:"developers@xone.org",
  Work_Email:"job@xone.org",
  Community_Email:"community@xone.org",
};
